import 'package:flutter/foundation.dart';
import 'learning_skill.dart';

/// The pedagogical classification of the next recommended learning action.
enum RecommendationType {
  continueLesson,
  reviewVocabulary,
  practiceWeakSkill,
  repeatDifficultConcept,
  startConversation,
  advanceToNextLesson,
}

/// Structured recommendation generated by the Adaptive Learning Engine.
@immutable
class LearningRecommendation {
  final RecommendationType type;
  final String titleArabic;
  final String titleEnglish;
  final String subtitleArabic;
  final String subtitleEnglish;
  final String? targetLessonId;
  final LearningSkill? targetSkill;
  final String actionRoute;
  final int urgencyScore; // Higher score = higher priority

  const LearningRecommendation({
    required this.type,
    required this.titleArabic,
    required this.titleEnglish,
    required this.subtitleArabic,
    required this.subtitleEnglish,
    this.targetLessonId,
    this.targetSkill,
    required this.actionRoute,
    this.urgencyScore = 50,
  });
}
